/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: '#f5f5f7',
        canvas: '#ffffff',
        canvasParchment: '#f5f5f7',
        surfacePearl: '#fafafc',
        surface: '#ffffff',
        surfaceVariant: '#f5f5f7',
        card: '#ffffff',
        pill: '#ffffff',
        primary: '#0066cc',
        primaryFocus: '#0071e3',
        primaryOnDark: '#2997ff',
        secondary: '#0066cc',
        accent: '#0066cc',
        ink: '#1d1d1f',
        body: '#1d1d1f',
        bodyMuted: '#86868b',
        deepBlack: '#1d1d1f',
        pureBlack: '#000000',
        text: '#1d1d1f',
        textSecondary: '#86868b',
        muted: '#86868b',
        border: '#e0e0e0',
        borderDark: '#d2d2d7',
        hairline: '#e0e0e0',
        dividerSoft: '#f0f0f0',
        success: '#34C759',
        error: '#FF3B30',
        warning: '#FF9500',
      },
      borderRadius: {
        'xs': '5px',
        'sm': '8px',
        'md': '11px',
        'lg': '16px',
        'xl': '20px',
        'pill': '9999px',
      }
    },
  },
  plugins: [],
}
